const initialValues = [
  { id: 1, ddElement: "American", isSelected: false, label: "cuisineType" },
  { id: 2, ddElement: "Asian", isSelected: false, label: "cuisineType" },
  { id: 3, ddElement: "British", isSelected: false, label: "cuisineType" },
  { id: 4, ddElement: "Caribbean", isSelected: false, label: "cuisineType" },
  {
    id: 5,
    ddElement: "Central Europe",
    isSelected: false,
    label: "cuisineType",
  },
  { id: 6, ddElement: "Chinese", isSelected: false, label: "cuisineType" },
  {
    id: 7,
    ddElement: "Eastern Europe",
    isSelected: false,
    label: "cuisineType",
  },
  { id: 8, ddElement: "French", isSelected: false, label: "cuisineType" },
  { id: 9, ddElement: "Indian", isSelected: false, label: "cuisineType" },
  { id: 10, ddElement: "Italian", isSelected: false, label: "cuisineType" },
  { id: 11, ddElement: "Japanese", isSelected: false, label: "cuisineType" },
  { id: 12, ddElement: "Kosher", isSelected: false, label: "cuisineType" },
  {
    id: 13,
    ddElement: "Mediterranean",
    isSelected: false,
    label: "cuisineType",
  },
  { id: 14, ddElement: "Mexican", isSelected: false, label: "cuisineType" },
  {
    id: 15,
    ddElement: "Middle Eastern",
    isSelected: false,
    label: "cuisineType",
  },
  { id: 16, ddElement: "Nordic", isSelected: false, label: "cuisineType" },
  {
    id: 17,
    ddElement: "South American",
    isSelected: false,
    label: "cuisineType",
  },
  {
    id: 18,
    ddElement: "South East Asian",
    isSelected: false,
    label: "cuisineType",
  },
  { id: 19, ddElement: "alcohol-free", isSelected: false, label: "health" },
  {
    id: 20,
    ddElement: "immuno-supportive",
    isSelected: false,
    label: "health",
  },
  { id: 21, ddElement: "celery-free", isSelected: false, label: "health" },
  { id: 22, ddElement: "crustacean-free", isSelected: false, label: "health" },
  { id: 23, ddElement: "dairy-free", isSelected: false, label: "health" },
  { id: 24, ddElement: "egg-free", isSelected: false, label: "health" },
  { id: 25, ddElement: "fish-free", isSelected: false, label: "health" },
  { id: 26, ddElement: "fodmap-free", isSelected: false, label: "health" },
  { id: 27, ddElement: "gluten-free", isSelected: false, label: "health" },
  { id: 28, ddElement: "keto-friendly", isSelected: false, label: "health" },
  { id: 29, ddElement: "kidney-friendly", isSelected: false, label: "health" },
  { id: 30, ddElement: "kosher", isSelected: false, label: "health" },
  { id: 31, ddElement: "low-potassium", isSelected: false, label: "health" },
  { id: 32, ddElement: "lupine-free", isSelected: false, label: "health" },
  { id: 33, ddElement: "mustard-free", isSelected: false, label: "health" },
  { id: 34, ddElement: "low-fat-abs", isSelected: false, label: "health" },
  { id: 35, ddElement: "No-oil-added", isSelected: false, label: "health" },
  { id: 36, ddElement: "low-sugar", isSelected: false, label: "health" },
  { id: 37, ddElement: "paleo", isSelected: false, label: "health" },
  { id: 38, ddElement: "peanut-free", isSelected: false, label: "health" },
  { id: 39, ddElement: "pecatarian", isSelected: false, label: "health" },
  { id: 40, ddElement: "pork-free", isSelected: false, label: "health" },
  { id: 41, ddElement: "red-meat-free", isSelected: false, label: "health" },
  { id: 42, ddElement: "sesame-free", isSelected: false, label: "health" },
  { id: 43, ddElement: "shellfish-free", isSelected: false, label: "health" },
  { id: 44, ddElement: "soy-free", isSelected: false, label: "health" },
  { id: 45, ddElement: "sugar-conscious", isSelected: false, label: "health" },
  { id: 46, ddElement: "tree-nut-free", isSelected: false, label: "health" },
  { id: 47, ddElement: "vegan", isSelected: false, label: "health" },
  { id: 48, ddElement: "vegetarian", isSelected: false, label: "health" },
  { id: 49, ddElement: "wheat-free", isSelected: false, label: "health" },
  { id: 50, ddElement: "Breakfast", isSelected: false, label: "mealType" },
  { id: 51, ddElement: "Lunch", isSelected: false, label: "mealType" },
  { id: 52, ddElement: "Dinner", isSelected: false, label: "mealType" },
  { id: 53, ddElement: "Snack", isSelected: false, label: "mealType" },
  { id: 54, ddElement: "Teatime", isSelected: false, label: "mealType" },
  {
    id: 55,
    ddElement: "Alcohol-cocktail",
    isSelected: false,
    label: "dishType",
  },
  {
    id: 56,
    ddElement: "Biscuits and cookies",
    isSelected: false,
    label: "dishType",
  },
  { id: 57, ddElement: "Bread", isSelected: false, label: "dishType" },
  { id: 58, ddElement: "Cereals", isSelected: false, label: "dishType" },
  {
    id: 59,
    ddElement: "Condiments and sauces",
    isSelected: false,
    label: "dishType",
  },
  { id: 60, ddElement: "Drinks", isSelected: false, label: "dishType" },
  { id: 61, ddElement: "Desserts", isSelected: false, label: "dishType" },
  { id: 62, ddElement: "Egg", isSelected: false, label: "dishType" },
  { id: 63, ddElement: "Main course", isSelected: false, label: "dishType" },
  { id: 64, ddElement: "Omelet", isSelected: false, label: "dishType" },
  { id: 65, ddElement: "Pancake", isSelected: false, label: "dishType" },
  { id: 66, ddElement: "Preps", isSelected: false, label: "dishType" },
  { id: 67, ddElement: "Preserve", isSelected: false, label: "dishType" },
  { id: 68, ddElement: "Salad", isSelected: false, label: "dishType" },
  { id: 69, ddElement: "Sandwiches", isSelected: false, label: "dishType" },
  { id: 70, ddElement: "Soup", isSelected: false, label: "dishType" },
  { id: 71, ddElement: "Starter", isSelected: false, label: "dishType" },
];

export default initialValues;
